name: Italcaribe Club
favicon: null
layout_spectrum: 0.25023
typography_spectrum: 0.25465
title: Benvenuti nel mondo Italcaribe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#014df8'
    - '#eeff00'
    - '#190343'
    - '#ff68f8'
    - '#55b6fb'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
