name: Italcaribe Club
favicon: null
layout_spectrum: 0.25183
typography_spectrum: 0.9622558332048357
title: Vacanze ai Caraibi LowCost - Viaggi e vacanze Miami
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002049'
    - '#004580'
    - '#e5e5e3'
    - '#0179b5'
    - '#01b09f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.11636208882555366
  rhythmicContrast: 0.5
purpose: []
